/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edcaron.md5check.visao;

import br.edcaron.md5check.controle.MD5;
import java.io.File;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import br.edcaron.md5check.modelo.Arquivo;
import br.edcaron.md5check.daos.ArquivoDAO;

/**
 *
 * @author eduardo.caron
 */
public class TelaPrincipal extends javax.swing.JFrame {

    ArrayList<Arquivo> listaArquivos = new ArrayList();
    ArrayList<Arquivo> listaDuplicados = new ArrayList();
    ArrayList<Arquivo> listaNovos = new ArrayList();

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível usar a aparência do Sistema.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Funcao para limpar o conteudo dos campos editaveis da tela
     */
    protected void limparTelasListas() {
        listaArquivos.clear();
        listaNovos.clear();
        listaDuplicados.clear();

        jtaEnviados.setText("");
        jtaDuplicados.setText("");
        jtaNovos.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtaEnviados = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaDuplicados = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaNovos = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtnSelecionar = new javax.swing.JButton();
        jbtnApagar = new javax.swing.JButton();
        jbtnAdicionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtaEnviados.setColumns(20);
        jtaEnviados.setRows(5);
        jScrollPane1.setViewportView(jtaEnviados);

        jtaDuplicados.setColumns(20);
        jtaDuplicados.setRows(5);
        jScrollPane2.setViewportView(jtaDuplicados);

        jtaNovos.setColumns(20);
        jtaNovos.setRows(5);
        jScrollPane3.setViewportView(jtaNovos);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Duplicados:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Novos:");

        jbtnSelecionar.setText("Selecionar Arquivos");
        jbtnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSelecionarActionPerformed(evt);
            }
        });

        jbtnApagar.setText("Apagar Duplicados");
        jbtnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnApagarActionPerformed(evt);
            }
        });

        jbtnAdicionar.setText("Adicionar arquivos novos ao BD");
        jbtnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnSelecionar)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnApagar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnAdicionar)))
                        .addGap(0, 595, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnSelecionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnApagar)
                    .addComponent(jbtnAdicionar))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSelecionarActionPerformed
//        SelecionarArquivo as = new SelecionarArquivo();
//        as.setVisible(true);

        JFileChooser fc = new JFileChooser();
        fc.setMultiSelectionEnabled(true);

        DecimalFormat dec = new DecimalFormat("0.00");

        int r = fc.showOpenDialog(this);

        if (r == JFileChooser.APPROVE_OPTION) {
            limparTelasListas();
            File[] arquivos = fc.getSelectedFiles();

            for (File arquivo : arquivos) {
       
                Arquivo a = new Arquivo();
                a.setDiretorio(arquivo.toString());
                a.setTamanho(br.edcaron.md5check.controle.Util.converterByteParaKBouMB(arquivo));
                a.setMd5(MD5.geraHash(arquivo));

                listaArquivos.add(a);

                jtaEnviados.append(a.getDiretorio() + " Tamanho: " + a.getTamanho() + "\n");
            }

            ArrayList<ArrayList> listaListas = new ArrayList();

            listaListas = new ArquivoDAO().verificarDuplicados(listaArquivos);

            listaDuplicados = listaListas.get(0);
            listaNovos = listaListas.get(1);

            for (Arquivo arq : listaDuplicados) {
                jtaDuplicados.append(arq.getDiretorio() + " Tamanho: " + arq.getTamanho() + "\n");
            }

            for (Arquivo arq : listaNovos) {
                jtaNovos.append(arq.getDiretorio() + " Tamanho: " + arq.getTamanho() + "\n");
            }

        }
    }//GEN-LAST:event_jbtnSelecionarActionPerformed

    private void jbtnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnApagarActionPerformed
        if (jtaDuplicados.getText().trim().length() != 0) {
            int apagados = 0;
            for (Arquivo arq : listaDuplicados) {
                br.edcaron.md5check.controle.Util.apagarArquivo(arq.getDiretorio());
                apagados++;
            }
            JOptionPane.showMessageDialog(null, apagados + " arquivos foram apagados");
            limparTelasListas();
        }
    }//GEN-LAST:event_jbtnApagarActionPerformed

    private void jbtnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdicionarActionPerformed
        if (jtaNovos.getText().trim().length() != 0) {
            ArquivoDAO adao = new ArquivoDAO();
            String adicionados = adao.salvar(listaNovos);
            JOptionPane.showMessageDialog(null, adicionados + " arquivos foram adicionados");
            limparTelasListas();
        }
    }//GEN-LAST:event_jbtnAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtnAdicionar;
    private javax.swing.JButton jbtnApagar;
    private javax.swing.JButton jbtnSelecionar;
    private javax.swing.JTextArea jtaDuplicados;
    private javax.swing.JTextArea jtaEnviados;
    private javax.swing.JTextArea jtaNovos;
    // End of variables declaration//GEN-END:variables
}
